#include "VibH2OBubbleActor.h"

#include "Components/StaticMeshComponent.h"
#include "Components/TextRenderComponent.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "UObject/ConstructorHelpers.h"
#include "VibH2OModule.h"

AVibH2OBubbleActor::AVibH2OBubbleActor()
{
	// The bubble does not tick on its own: the stage actor places and updates
	// it, in a controlled order. Two hundred actors each ticking independently
	// cost more and coordinate worse than a single loop.
	PrimaryActorTick.bCanEverTick = false;

	BubbleRoot = CreateDefaultSubobject<USceneComponent>(TEXT("BubbleRoot"));
	SetRootComponent(BubbleRoot);

	DemoMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DemoMesh"));
	DemoMesh->SetupAttachment(BubbleRoot);
	DemoMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	DemoMesh->SetGenerateOverlapEvents(false);
	DemoMesh->SetCastShadow(true);

	SeatLabel = CreateDefaultSubobject<UTextRenderComponent>(TEXT("SeatLabel"));
	SeatLabel->SetupAttachment(BubbleRoot);
	SeatLabel->SetHorizontalAlignment(EHTA_Center);
	SeatLabel->SetVerticalAlignment(EVRTA_TextCenter);
	SeatLabel->SetWorldSize(26.0f);
	SeatLabel->SetTextRenderColor(FColor(255, 255, 255));
	SeatLabel->SetRelativeLocation(FVector(0.0f, 0.0f, 46.0f));
	SeatLabel->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	SeatLabel->SetGenerateOverlapEvents(false);
	SeatLabel->SetCastShadow(false);
	// Off by default: the numbers are a checking aid, not part of the piece.
	SeatLabel->SetVisibility(false);

	// Demonstration sphere, taken from engine content. It proves the data
	// flows, nothing more.
	static ConstructorHelpers::FObjectFinder<UStaticMesh> SphereMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"));
	if (SphereMesh.Succeeded())
	{
		DemoMesh->SetStaticMesh(SphereMesh.Object);
		DemoMesh->SetRelativeScale3D(FVector(0.35f));
	}

	// The demonstration material lives in the plugin's own content and is
	// generated by Tools/make_demo_material.py. Optional finder: its absence
	// is not an error - an artist Blueprint replaces all of this anyway.
	static ConstructorHelpers::FObjectFinderOptional<UMaterialInterface> DemoMaterial(TEXT("/VibH2O/M_VibH2ODemoBubble.M_VibH2ODemoBubble"));
	if (DemoMaterial.Get() != nullptr)
	{
		DemoMesh->SetMaterial(0, DemoMaterial.Get());
	}
}

void AVibH2OBubbleActor::BeginPlay()
{
	Super::BeginPlay();
	GetOrCreateMaterial();
}

UMaterialInstanceDynamic* AVibH2OBubbleActor::GetOrCreateMaterial()
{
	if (DynamicMaterial != nullptr)
	{
		return DynamicMaterial;
	}

	UMeshComponent* Target = TargetMeshComponent;
	if (Target == nullptr)
	{
		// No component designated: take the first mesh we find. That spares the
		// artist from wiring anything up in the simple case.
		TArray<UMeshComponent*> Meshes;
		GetComponents<UMeshComponent>(Meshes);
		if (Meshes.Num() > 0)
		{
			Target = Meshes[0];
			TargetMeshComponent = Target;
		}
	}

	if (Target == nullptr)
	{
		return nullptr;
	}

	DynamicMaterial = Target->CreateAndSetMaterialInstanceDynamic(MaterialSlot);
	return DynamicMaterial;
}

void AVibH2OBubbleActor::SetMaterialTarget(UMeshComponent* InMesh, int32 InSlot)
{
	TargetMeshComponent = InMesh;
	MaterialSlot = FMath::Max(InSlot, 0);
	DynamicMaterial = nullptr;
	GetOrCreateMaterial();
}

void AVibH2OBubbleActor::AssignSeat(const FVibH2OSeat& Seat)
{
	SeatIndex = Seat.SeatIndex;
	IndividualId = Seat.IndividualId;
	Column = Seat.Column;
	Row = Seat.Row;

	// The previous position no longer means anything. Without this reset the
	// measured speed would spike at assignment time and the striations would
	// shoot off.
	bHasPreviousLocation = false;
	MeasuredSpeed = 0.0f;
	LastBeatCount = 0;

	// WITH_EDITOR, and not a build-configuration macro: SetActorLabel only
	// exists when the editor is compiled in. A Development Game build - the one
	// used in rehearsal - has no editor and would not link.
	if (SeatLabel != nullptr)
	{
		SeatLabel->SetText(FText::AsNumber(IndividualId));
	}

#if WITH_EDITOR
	SetActorLabel(FString::Printf(TEXT("Bubble_S%03d_I%03d"), SeatIndex, IndividualId));
#endif

	ReceiveSeatAssigned(SeatIndex, IndividualId);
}

void AVibH2OBubbleActor::SetSeatLabelVisible(bool bVisible)
{
	if (SeatLabel != nullptr && SeatLabel->IsVisible() != bVisible)
	{
		SeatLabel->SetVisibility(bVisible);
	}
}

void AVibH2OBubbleActor::OrientSeatLabel(const FVector& ViewLocation)
{
	if (SeatLabel == nullptr || !SeatLabel->IsVisible())
	{
		return;
	}
	// Toward the viewer, not away from them: pointing the text's forward axis
	// away renders its back face, and the digits come out mirrored. Measured on
	// a capture - "17" read as its own reflection.
	const FVector Toward = ViewLocation - SeatLabel->GetComponentLocation();
	if (Toward.SizeSquared() > KINDA_SMALL_NUMBER)
	{
		SeatLabel->SetWorldRotation(Toward.Rotation());
	}
}

void AVibH2OBubbleActor::UpdateFromState(const FVibH2OIndividualState& NewState, float InFocusMask, const FLinearColor& Tint,
	float CollectiveSynchrony, float BlendAlpha, float StriationScale, float DeltaTime)
{
	State = NewState;
	FocusMask = InFocusMask;

	// Speed measured in LOCAL space. That is a choice: measuring in world space
	// would send the striations racing the moment the stage actor is moved or
	// animated, even though the bubble has not moved within the room.
	const FVector LocalLocation = GetRootComponent() ? GetRootComponent()->GetRelativeLocation() : FVector::ZeroVector;
	if (bHasPreviousLocation && DeltaTime > SMALL_NUMBER)
	{
		const float Instant = static_cast<float>((LocalLocation - PreviousLocalLocation).Size()) / DeltaTime;
		// Short smoothing: raw speed is noisy frame to frame, and a flickering
		// striation shows.
		MeasuredSpeed = FMath::FInterpTo(MeasuredSpeed, Instant, DeltaTime, 8.0f);
	}
	PreviousLocalLocation = LocalLocation;
	bHasPreviousLocation = true;

	if (State.BeatCount != LastBeatCount)
	{
		LastBeatCount = State.BeatCount;
		OnBeat.Broadcast(State.BeatCount);
		ReceiveBeat(State.BeatCount);
	}

	PushMaterialParameters(Tint, CollectiveSynchrony, BlendAlpha, StriationScale);

	OnDataUpdated.Broadcast(State);
	ReceiveDataUpdated(State);
}

void AVibH2OBubbleActor::PushMaterialParameters(const FLinearColor& Tint, float CollectiveSynchrony, float BlendAlpha, float StriationScale)
{
	UMaterialInstanceDynamic* Material = GetOrCreateMaterial();
	if (Material == nullptr)
	{
		return;
	}

	auto SetScalar = [Material](const FName& Name, float Value)
	{
		// An empty name disables the send, so the artist can remove a parameter
		// from their material without the plugin complaining.
		if (!Name.IsNone())
		{
			Material->SetScalarParameterValue(Name, Value);
		}
	};

	SetScalar(ParameterNames.BeatPhase, State.BeatPhase);
	SetScalar(ParameterNames.BeatPulse, State.BeatPulse);
	SetScalar(ParameterNames.Bpm, State.Bpm);
	SetScalar(ParameterNames.Excitation, State.Excitation);
	SetScalar(ParameterNames.Synchrony, State.Synchrony);
	SetScalar(ParameterNames.StriationSpeed, MeasuredSpeed * StriationScale);
	SetScalar(ParameterNames.FocusMask, FocusMask);
	SetScalar(ParameterNames.Staleness, State.bStale ? 1.0f : 0.0f);
	SetScalar(ParameterNames.CollectiveSynchrony, CollectiveSynchrony);
	SetScalar(ParameterNames.BlendAlpha, BlendAlpha);

	if (!ParameterNames.TintColor.IsNone())
	{
		Material->SetVectorParameterValue(ParameterNames.TintColor, Tint);
	}
}
