#include "VibH2OWaterMotes.h"

#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Layout/VibH2OLayoutMath.h"
#include "Materials/MaterialInterface.h"
#include "UObject/ConstructorHelpers.h"
#include "VibH2OModule.h"

AVibH2OWaterMotes::AVibH2OWaterMotes()
{
	PrimaryActorTick.bCanEverTick = true;
	// Drift the field in the editor too: still water reads as a photograph.
	PrimaryActorTick.bStartWithTickEnabled = true;

	SetRootComponent(CreateDefaultSubobject<USceneComponent>(TEXT("MotesRoot")));

	static ConstructorHelpers::FObjectFinder<UStaticMesh> Sphere(TEXT("/Engine/BasicShapes/Sphere.Sphere"));
	if (Sphere.Succeeded())
	{
		MoteMesh = Sphere.Object;
	}

	// Generated by Tools/make_demo_material.py. Optional: without it the motes
	// render with the default material instead of failing to load.
	static ConstructorHelpers::FObjectFinderOptional<UMaterialInterface> Material(TEXT("/VibH2O/M_VibH2OMote.M_VibH2OMote"));
	if (Material.Get() != nullptr)
	{
		MoteMaterial = Material.Get();
	}
}

void AVibH2OWaterMotes::OnConstruction(const FTransform& Transform)
{
	Super::OnConstruction(Transform);
	Rebuild();
}

void AVibH2OWaterMotes::BeginPlay()
{
	Super::BeginPlay();
	if (Spawned.Num() == 0)
	{
		Rebuild();
	}
}

void AVibH2OWaterMotes::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	if (FMath::IsNearlyZero(CurrentSpeed))
	{
		return;
	}

	// One rotation for the whole field. Animating motes individually would cost
	// hundreds of transform updates a frame to say the same thing, and
	// suspended silt really does drift as one body in a current.
	AddActorLocalRotation(FRotator(0.0f, CurrentSpeed * 360.0f * DeltaSeconds, 0.0f));
}

bool AVibH2OWaterMotes::ShouldTickIfViewportsOnly() const
{
	return true;
}

void AVibH2OWaterMotes::Rebuild()
{
	for (UStaticMeshComponent* Mote : Spawned)
	{
		if (IsValid(Mote))
		{
			Mote->DestroyComponent();
		}
	}
	Spawned.Reset();

	const int32 Total = FMath::Clamp(Count, 0, 800);
	if (Total == 0 || MoteMesh == nullptr)
	{
		return;
	}

	// Plain mesh components rather than one instanced component.
	//
	// The instanced path was tried first - one draw call for thousands of
	// motes, which is the textbook answer - and every instance rendered solid
	// black in this scene, with the same material that renders correctly on an
	// ordinary component. That was measured side by side, one control sphere
	// per material, before giving up on it. A few hundred tiny meshes on the
	// path that demonstrably works beats thousands on the one that does not,
	// and the room was running at five hundred frames a second with room to
	// spare.
	Spawned.Reserve(Total);

	for (int32 Index = 0; Index < Total; ++Index)
	{
		const int32 S = Seed * 977 + Index * 31;

		// Square-rooted radius keeps the density even across the disc: without
		// it every mote crowds into the middle.
		const float Angle = FVibH2ONoise::UnitFloat(S + 1) * 2.0f * PI;
		const float R = FMath::Sqrt(FVibH2ONoise::UnitFloat(S + 2)) * Radius;
		const float Z = FVibH2ONoise::SignedFloat(S + 3) * Height * 0.5f;

		// Size on a cubed curve: many small specks, a few large ones, which is
		// what reads as depth rather than a uniform dot screen.
		const float T = FVibH2ONoise::UnitFloat(S + 4);
		const float Size = FMath::Lerp(MinSize, MaxSize, T * T * T);

		UStaticMeshComponent* Mote = NewObject<UStaticMeshComponent>(this);
		if (Mote == nullptr)
		{
			continue;
		}

		Mote->SetupAttachment(GetRootComponent());
		Mote->SetMobility(EComponentMobility::Movable);
		Mote->SetStaticMesh(MoteMesh);
		if (MoteMaterial != nullptr)
		{
			Mote->SetMaterial(0, MoteMaterial);
		}
		Mote->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		Mote->SetGenerateOverlapEvents(false);
		Mote->SetCastShadow(false);
		Mote->SetRelativeLocation(FVector(R * FMath::Cos(Angle), R * FMath::Sin(Angle), Z));
		Mote->SetRelativeScale3D(FVector(Size * 0.01f));
		Mote->RegisterComponent();

		Spawned.Add(Mote);
	}
}
